<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="48184" started-at="2017-07-29T10:12:04Z" finished-at="2017-07-29T10:12:52Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="48184" started-at="2017-07-29T10:12:04Z" finished-at="2017-07-29T10:12:52Z">
      <class name="com.companyname.projectname.testscripts.TestLoginThroughDataProvider">
        <test-method status="PASS" signature="setUP()[pri:0, instance:com.companyname.projectname.testscripts.TestLoginThroughDataProvider@77cd7a0]" name="setUP" is-config="true" duration-ms="38250" started-at="2017-07-29T15:42:04Z" finished-at="2017-07-29T15:42:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method status="FAIL" signature="TestLoginWithDataProvider(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.companyname.projectname.testscripts.TestLoginThroughDataProvider@77cd7a0]" name="TestLoginWithDataProvider" duration-ms="2289" started-at="2017-07-29T15:42:43Z" data-provider="loginData" finished-at="2017-07-29T15:42:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC001]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test902@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[password]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Y]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.companyname.projectname.pagelibrary.SignIn.clickonSignIn(SignIn.java:44)
	at com.companyname.projectname.pagelibrary.SignIn.loginToApplication(SignIn.java:90)
	at com.companyname.projectname.testscripts.TestLoginThroughDataProvider.TestLoginWithDataProvider(TestLoginThroughDataProvider.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLoginWithDataProvider -->
        <test-method status="FAIL" signature="TestLoginWithDataProvider(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.companyname.projectname.testscripts.TestLoginThroughDataProvider@77cd7a0]" name="TestLoginWithDataProvider" duration-ms="1710" started-at="2017-07-29T15:42:45Z" data-provider="loginData" finished-at="2017-07-29T15:42:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC002]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test902@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[password]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Y]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.companyname.projectname.pagelibrary.SignIn.clickonSignIn(SignIn.java:44)
	at com.companyname.projectname.pagelibrary.SignIn.loginToApplication(SignIn.java:90)
	at com.companyname.projectname.testscripts.TestLoginThroughDataProvider.TestLoginWithDataProvider(TestLoginThroughDataProvider.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLoginWithDataProvider -->
        <test-method status="FAIL" signature="TestLoginWithDataProvider(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.companyname.projectname.testscripts.TestLoginThroughDataProvider@77cd7a0]" name="TestLoginWithDataProvider" duration-ms="1655" started-at="2017-07-29T15:42:47Z" data-provider="loginData" finished-at="2017-07-29T15:42:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC003]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test902@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[password]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[N]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.companyname.projectname.pagelibrary.SignIn.clickonSignIn(SignIn.java:44)
	at com.companyname.projectname.pagelibrary.SignIn.loginToApplication(SignIn.java:90)
	at com.companyname.projectname.testscripts.TestLoginThroughDataProvider.TestLoginWithDataProvider(TestLoginThroughDataProvider.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLoginWithDataProvider -->
        <test-method status="FAIL" signature="TestLoginWithDataProvider(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.companyname.projectname.testscripts.TestLoginThroughDataProvider@77cd7a0]" name="TestLoginWithDataProvider" duration-ms="1648" started-at="2017-07-29T15:42:48Z" data-provider="loginData" finished-at="2017-07-29T15:42:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC004]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test902@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[password]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Y]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.companyname.projectname.pagelibrary.SignIn.clickonSignIn(SignIn.java:44)
	at com.companyname.projectname.pagelibrary.SignIn.loginToApplication(SignIn.java:90)
	at com.companyname.projectname.testscripts.TestLoginThroughDataProvider.TestLoginWithDataProvider(TestLoginThroughDataProvider.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLoginWithDataProvider -->
        <test-method status="FAIL" signature="TestLoginWithDataProvider(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.companyname.projectname.testscripts.TestLoginThroughDataProvider@77cd7a0]" name="TestLoginWithDataProvider" duration-ms="1690" started-at="2017-07-29T15:42:50Z" data-provider="loginData" finished-at="2017-07-29T15:42:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC005]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test902@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[password]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Y]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.companyname.projectname.pagelibrary.SignIn.clickonSignIn(SignIn.java:44)
	at com.companyname.projectname.pagelibrary.SignIn.loginToApplication(SignIn.java:90)
	at com.companyname.projectname.testscripts.TestLoginThroughDataProvider.TestLoginWithDataProvider(TestLoginThroughDataProvider.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLoginWithDataProvider -->
        <test-method status="PASS" signature="quitBrowser()[pri:0, instance:com.companyname.projectname.testscripts.TestLoginThroughDataProvider@77cd7a0]" name="quitBrowser" is-config="true" duration-ms="72" started-at="2017-07-29T15:42:52Z" finished-at="2017-07-29T15:42:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- com.companyname.projectname.testscripts.TestLoginThroughDataProvider -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
